# netlify.toml

[build]
  command = "npm run build"
  publish = "frontend/dist"
  base = "frontend"

[functions]
  directory = "netlify/functions"


[build.environment]
  MONGODB_URI = "env:MONGODB_URI"
  GOOGLE_MAPS_API_KEY = "env:GOOGLE_MAPS_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
